//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AdminUser
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập tên")]
        [DisplayName("Tên User")]
        [StringLength(50,MinimumLength =5,ErrorMessage ="Tên phải nhiều hơn 5 ký tự và it hơn 50 ký tự")]
        public string NameUser { get; set; }
        [DisplayName("Vị trí")]
        public string RoleUser { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập mật khẩu")]
        [DisplayName("Mật khẩu")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage ="Vui lòng nhập số điện thoại")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber1 { get; set; }
        [DisplayName("Gmail")]
        [Required(ErrorMessage ="Vui lòng nhập gmail")]
        [DataType(DataType.EmailAddress)]
        public string gmail { get; set; }
    }
}
